[project]
name = "hand-visual"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.32",
    "opencv-python>=4.13.0.90",
    "pydantic>=2.12.5",
]
